### ISSUE TITLE
[FEATURE] Add support for Slack user groups in rotations

### ISSUE THREAD

**Issue by gabriel-loo** [pilosus/dienstplan#115]
Slack provides the ability to create [user groups](https://slack.com/help/articles/212906697-Create-a-user-group) to group multiple people together under the same @ handle (e.g. `@designers`). In some cases, duty rotations apply to user groups rather than to individuals. For example, if I want to assign bug triaging responsibilities to a different team each week, I'd like set that up with the following command:
```
@dienstplan create bug-triaging @teamA @teamB @teamC
It is your team's turn this week to triage new bug tickets in the backlog.
```

I think the command currently fails because the formatting is different between mentioning user groups and individual users.

[User group ID format](https://api.slack.com/reference/surfaces/formatting#mentioning-groups): `<!subteam^S123ABC456>`
[Individual user ID format](https://api.slack.com/reference/surfaces/formatting#mentioning-users): `<@U123ABC456>`

Could dienstplan be updated to support rotating Slack user groups in addition to individual users?

**Comment by pilosus** [comment]
Hi @gabriel-loo!

I think we can support user groups.

There are a few things to consider:

1. The Slack API endpoint for listing users of a user group [usergroups.users.list](https://api.slack.com/methods/usergroups.users.list) says nothing about the order. Is it deterministic? Is it guaranteed that requesting the endpoint multiple times yields the same results as long as no user added or removed? If it's deterministic, then we can rely on the endpoint without saving user ids of the group to the database and be sure round-robin rotations work properly. If it's not, then we will need to save the users to the database and subscribe to the events of the usergroup changes (new user added, user removed, etc.). We can probably use one of these:

- [subteam_members_changed](https://api.slack.com/events/subteam_members_changed)
- [subteam_updated](https://api.slack.com/events/subteam_updated)

2. What happens if a user of a usergroup gets removed from the usergroup while the user is a current duty in `dienstplan` rotation? Probably, it should be an equivalent of `@dienstplan update` that recreates the rota and assigns current duty to the first user in the usergroup.

**Comment by gabriel-loo** [comment]
Hi @pilosus,

I was actually thinking of treating user groups handles the same way individual users are managed.

Using this example:
```
@dienstplan create bug-triaging @teamA @teamB @teamC
It is your team's turn this week to triage new bug tickets in the backlog.
```
This would first assign the rotation to `@teamA` (and not just the first user in team A).

---

```
@dienstplan rotate bug-triaging
```
This would set it to `@teamB` which is next in the rotation.

---
```
@dienstplan who bug-triaging
```
would show
```
Hey @teamB, you are an on-call person for `bug-triaging` rotation.
It is your team's turn this week to triage new bug tickets in the backlog.
```
(Note: we may have to switch it to "you are on call for..." rather than "you are the on-call person for...")

**Comment by pilosus** [comment]
@gabriel-loo ah, I see what you mean. Yes, it makes sense to support this kind of mention, i.e. `dienstplan` doesn't care if it's an individual user or a user group, it just uses the entity in rotation.

I should be probably easy to do: the regex [here](https://github.com/pilosus/dienstplan/blob/b927d42f23d9a8545c3a402a61a5c85896cf3780/src/dienstplan/commands.clj#L255) must be amended to something like:

```
(?s)(?<userid>\<(@|!subteam\^)[A-Z0-9]+\>)
```

but I haven't test it myself.

Plus, the wording [here](https://github.com/pilosus/dienstplan/blob/b927d42f23d9a8545c3a402a61a5c85896cf3780/src/dienstplan/commands.clj#L488).

If you want to draft a PR feel free to do so.
Otherwise, I'd be able to do it myself in a couple of weeks.

**Comment by pilosus** [comment]
@gabriel-loo done in release [1.1.109](https://github.com/pilosus/dienstplan/releases/tag/1.1.109)
