### ISSUE TITLE
Rotate command to show next person in rotation

### ISSUE THREAD

**Issue by BurlakovNick** [pilosus/dienstplan#35]
Would be nice if rotate command show some proof of work. After rotation this message appeared:
```
dienstplanAPP Today at 11:00 AM
Users in rotation duty of channel compliance-devs have been rotated
```
But it left me wondering who's the next person in rotation, and what actually happened. 

This message could be different, like this:
```
Users ... have been rotated, from: %USERNAME%, to: %USERNAME%
```

**Comment by pilosus** [comment]
Sounds good. The only thing I don't want to happen is user mentions. That may be irritating to receive so many irrelevant user mentions. There's also a dedicated command `who` for it. The user id is stored in the DB. It's auto-converted to user mention when posted as `<@user-id>`. 
We may want to call [users.info](https://api.slack.com/methods/users.info) API method and retrieve `user.name` for both `from` and `two` users and user names instead of the mentions
