### ISSUE TITLE
[FEATURE] Update text of duties description

### ISSUE THREAD

**Issue by maradik** [pilosus/dienstplan#66]
**Is your feature request related to a problem? Please describe.**
I wanna change text of `duties description` for a rotation but the only way to do it is to re-create the rotation.

**Describe the solution you'd like**
Would be great to have something like this:
`@dienstplan update-description <rotation name> <duties description>`

**Comment by pilosus** [comment]
Related to p2. in the [issue 65](https://github.com/pilosus/dienstplan/issues/65#issuecomment-1298954461).
I'd suggest to keep things simple: instead of `update-description` use `update`. It will require to update both `<list of user mentions>` and  `<duties description>`. But usually it's a not a big deal to copy-paste the list of mentions from the previous rota state, and it will spare time from implementing `update-user-mentions` later :-)

**Comment by pilosus** [comment]
@maradik done in the release [0.4.0](https://github.com/pilosus/dienstplan/releases/tag/0.4.0).
Docker image is [available](https://hub.docker.com/layers/pilosus/dienstplan/0.4.0/images/sha256-588fc1ca3b68373ef91bf5424545d1feb66ef2c853f2da8903c4fd5e2a266fc7?context=explore) as well.

I consider the issue to be resolved. In case of any problems, please file a new issue.
